#include "model.h"
#include "model.data"

#if INTERFACE

typedef struct {
    int Width;
    int Height;
    int Length;
    V2 *Data;
} Model;

typedef struct {
    int Height;
    int Length;
    Model Characters[];
} ModelFont;

#endif

ModelFont BattleFont = {
    .Height = 85,
    .Length = 128,
    .Characters = {
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 56,
            .Height = 85,
            .Length = 0,
            .Data = BattleChar32Data,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar48Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 2,
            .Data = BattleChar49Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 10,
            .Data = BattleChar50Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar51Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar52Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 10,
            .Data = BattleChar53Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar54Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 4,
            .Data = BattleChar55Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 10,
            .Data = BattleChar56Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar57Data,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 56,
            .Height = 85,
            .Length = 10,
            .Data = BattleChar97Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 22,
            .Data = BattleChar98Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar99Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 12,
            .Data = BattleChar100Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar101Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar102Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 12,
            .Data = BattleChar103Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar104Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar105Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar106Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar107Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 4,
            .Data = BattleChar108Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar109Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar110Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar111Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar112Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 12,
            .Data = BattleChar113Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 10,
            .Data = BattleChar114Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 10,
            .Data = BattleChar115Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 4,
            .Data = BattleChar116Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar117Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 4,
            .Data = BattleChar118Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 8,
            .Data = BattleChar119Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 4,
            .Data = BattleChar120Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar121Data,
        },
        {
            .Width = 56,
            .Height = 85,
            .Length = 6,
            .Data = BattleChar122Data,
        },
        {},
        {},
        {},
        {},
        {},
    },
};

ModelFont SeparatorFont = {
    .Height = 100,
    .Length = 128,
    .Characters = {
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 30,
            .Height = 100,
            .Length = 0,
            .Data = SeparatorChar32Data,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 45,
            .Height = 100,
            .Length = 16,
            .Data = SeparatorChar48Data,
        },
        {
            .Width = 46,
            .Height = 100,
            .Length = 2,
            .Data = SeparatorChar49Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 22,
            .Data = SeparatorChar50Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 26,
            .Data = SeparatorChar51Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar52Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 20,
            .Data = SeparatorChar53Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 22,
            .Data = SeparatorChar54Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar55Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 32,
            .Data = SeparatorChar56Data,
        },
        {
            .Width = 45,
            .Height = 100,
            .Length = 22,
            .Data = SeparatorChar57Data,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 55,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar65Data,
        },
        {
            .Width = 44,
            .Height = 100,
            .Length = 20,
            .Data = SeparatorChar66Data,
        },
        {
            .Width = 43,
            .Height = 100,
            .Length = 18,
            .Data = SeparatorChar67Data,
        },
        {
            .Width = 43,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar68Data,
        },
        {
            .Width = 44,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar69Data,
        },
        {
            .Width = 44,
            .Height = 100,
            .Length = 6,
            .Data = SeparatorChar70Data,
        },
        {
            .Width = 43,
            .Height = 100,
            .Length = 18,
            .Data = SeparatorChar71Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 6,
            .Data = SeparatorChar72Data,
        },
        {
            .Width = 39,
            .Height = 100,
            .Length = 2,
            .Data = SeparatorChar73Data,
        },
        {
            .Width = 37,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar74Data,
        },
        {
            .Width = 53,
            .Height = 100,
            .Length = 6,
            .Data = SeparatorChar75Data,
        },
        {
            .Width = 40,
            .Height = 100,
            .Length = 4,
            .Data = SeparatorChar76Data,
        },
        {
            .Width = 60,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar77Data,
        },
        {
            .Width = 51,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar78Data,
        },
        {
            .Width = 48,
            .Height = 100,
            .Length = 16,
            .Data = SeparatorChar79Data,
        },
        {
            .Width = 43,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar80Data,
        },
        {
            .Width = 50,
            .Height = 100,
            .Length = 18,
            .Data = SeparatorChar81Data,
        },
        {
            .Width = 46,
            .Height = 100,
            .Length = 14,
            .Data = SeparatorChar82Data,
        },
        {
            .Width = 43,
            .Height = 100,
            .Length = 26,
            .Data = SeparatorChar83Data,
        },
        {
            .Width = 59,
            .Height = 100,
            .Length = 4,
            .Data = SeparatorChar84Data,
        },
        {
            .Width = 44,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar85Data,
        },
        {
            .Width = 51,
            .Height = 100,
            .Length = 4,
            .Data = SeparatorChar86Data,
        },
        {
            .Width = 79,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar87Data,
        },
        {
            .Width = 56,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar88Data,
        },
        {
            .Width = 48,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar89Data,
        },
        {
            .Width = 52,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar90Data,
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {
            .Width = 46,
            .Height = 100,
            .Length = 20,
            .Data = SeparatorChar97Data,
        },
        {
            .Width = 46,
            .Height = 100,
            .Length = 14,
            .Data = SeparatorChar98Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 18,
            .Data = SeparatorChar99Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 14,
            .Data = SeparatorChar100Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 20,
            .Data = SeparatorChar101Data,
        },
        {
            .Width = 48,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar102Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 22,
            .Data = SeparatorChar103Data,
        },
        {
            .Width = 49,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar104Data,
        },
        {
            .Width = 19,
            .Height = 100,
            .Length = 4,
            .Data = SeparatorChar105Data,
        },
        {
            .Width = 37,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar106Data,
        },
        {
            .Width = 48,
            .Height = 100,
            .Length = 14,
            .Data = SeparatorChar107Data,
        },
        {
            .Width = 39,
            .Height = 100,
            .Length = 2,
            .Data = SeparatorChar108Data,
        },
        {
            .Width = 67,
            .Height = 100,
            .Length = 16,
            .Data = SeparatorChar109Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar110Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 16,
            .Data = SeparatorChar111Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar112Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 12,
            .Data = SeparatorChar113Data,
        },
        {
            .Width = 42,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar114Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 26,
            .Data = SeparatorChar115Data,
        },
        {
            .Width = 39,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar116Data,
        },
        {
            .Width = 47,
            .Height = 100,
            .Length = 8,
            .Data = SeparatorChar117Data,
        },
        {
            .Width = 46,
            .Height = 100,
            .Length = 6,
            .Data = SeparatorChar118Data,
        },
        {
            .Width = 68,
            .Height = 100,
            .Length = 18,
            .Data = SeparatorChar119Data,
        },
        {
            .Width = 50,
            .Height = 100,
            .Length = 4,
            .Data = SeparatorChar120Data,
        },
        {
            .Width = 48,
            .Height = 100,
            .Length = 16,
            .Data = SeparatorChar121Data,
        },
        {
            .Width = 46,
            .Height = 100,
            .Length = 10,
            .Data = SeparatorChar122Data,
        },
        {},
        {},
        {},
        {},
        {},
    },
};

Model ModelAsteroid1 = {
    .Width = 317,
    .Height = 232,
    .Length = 24,
    .Data = Asteroid1Data,
};

Model ModelAsteroid2 = {
    .Width = 317,
    .Height = 258,
    .Length = 22,
    .Data = Asteroid2Data,
};

Model ModelAsteroid3 = {
    .Width = 317,
    .Height = 270,
    .Length = 24,
    .Data = Asteroid3Data,
};

Model ModelAsteroid4 = {
    .Width = 316,
    .Height = 275,
    .Length = 20,
    .Data = Asteroid4Data,
};

Model ModelBullet = {
    .Width = 42,
    .Height = 42,
    .Length = 2,
    .Data = BulletData,
};

Model ModelCat = {
    .Width = 133,
    .Height = 135,
    .Length = 38,
    .Data = CatData,
};

Model ModelShip = {
    .Width = 90,
    .Height = 121,
    .Length = 10,
    .Data = ShipData,
};

Model ModelSmallAsteroid1 = {
    .Width = 104,
    .Height = 105,
    .Length = 24,
    .Data = SmallAsteroid1Data,
};

Model ModelSmallAsteroid2 = {
    .Width = 96,
    .Height = 96,
    .Length = 20,
    .Data = SmallAsteroid2Data,
};

Model ModelTestShape = {
    .Width = 113,
    .Height = 107,
    .Length = 24,
    .Data = TestShapeData,
};
