const char *const BlendFragmentSource = ""
#if TARGET_OS_IPHONE
                                        "#version 300 es\n"
#else
                                        "#version 330\n"
#endif
                                        "precision highp float;\n"
                                        "\n"
                                        "in highp vec2 uv;\n"
                                        "\n"
                                        "uniform sampler2D original;\n"
                                        "uniform sampler2D bloom;\n"
                                        "\n"
                                        "out lowp vec4 color;\n"
                                        "\n"
                                        "void main() {\n"
                                        "    //    vec3 pixel = texture(original, uv).xyz;\n"
                                        "    //    if (pixel.x > 0.5) {\n"
                                        "    //        color = vec4((pixel - 0.5) * 2.0, 1.0);\n"
                                        "    //    } else {\n"
                                        "    //        color = vec4(0.0, 0.0, 0.0, 1.0);\n"
                                        "    //    }\n"
                                        "\n"
                                        "    //    color = clamp(texture(original, uv), 0.0, 0.5) + texture(bloom, uv) * 10.0;\n"
                                        "    // original is 0-1\n"
                                        "    //    color = clamp(texture(original, uv), 0.0, 0.5);\n"
                                        "    //    color = texture(original, uv);\n"
                                        "    //    color = texture(original, uv) + clamp(texture(bloom, uv) * 10.0, 0.0, 1.0);\n"
                                        "\n"
                                        "    vec4 bloom = clamp(texture(bloom, uv) * 10.0, 0.0, 1.0);\n"
                                        "    bloom *= vec4(0.5, 0.5, 1.0, 1.0);\n"
                                        "    color = texture(original, uv) + bloom;\n"
                                        "    //    color = texture(original, uv);\n"
                                        "    //    vec4 pixel = texture(original, uv);\n"
                                        "    //    if (pixel.x > 0.9) {\n"
                                        "    //        color = vec4(1, 0, 0, 1);\n"
                                        "    //        //        color = vec4((pixel - 0.5) * 2.0, 1.0);\n"
                                        "    //    } else {\n"
                                        "    //        color = pixel;\n"
                                        "    //        //        color = vec4(0.0, 0.0, 0.0, 1.0);\n"
                                        "    //    }\n"
                                        "\n"
                                        "    //    if (color.r > 0.5) {\n"
                                        "    //        color = vec4(1, 0, 0, 1);\n"
                                        "    //    }\n"
                                        "\n"
                                        "    //    color = texture(original, uv);\n"
                                        "    //                color = texture(original, uv);\n"
                                        "    //    vec4 pixel = texture(original, uv);\n"
                                        "    //    if (pixel.x > 0.9) {\n"
                                        "    //        color = pixel;\n"
                                        "    //    } else {\n"
                                        "    //        color = vec4(0.0, 0.0, 0.0, 1.0);\n"
                                        "    //    }\n"
                                        "    //    color = texture(bloom, uv);\n"
                                        "}\n"
                                        "";
const char *const BlendVertexSource = ""
#if TARGET_OS_IPHONE
                                      "#version 300 es\n"
#else
                                      "#version 330\n"
#endif
                                      "in highp vec2 position;\n"
                                      "out highp vec2 uv;\n"
                                      "\n"
                                      "void main() {\n"
                                      "    gl_Position = vec4(position, 0, 1);\n"
                                      "    uv = (position.xy + vec2(1, 1)) / 2.0;\n"
                                      "}\n"
                                      "";
const char *const BlurFragmentSource = ""
#if TARGET_OS_IPHONE
                                       "#version 300 es\n"
#else
                                       "#version 330\n"
#endif
                                       "precision highp float;\n"
                                       "\n"
                                       "uniform sampler2D tex;\n"
                                       "uniform bool horizontal;\n"
                                       "\n"
                                       "// http://dev.theomader.com/gaussian-kernel-calculator/\n"
                                       "// sigma=2 kernel=9\n"
                                       "const float weight[5] = float[](0.20236, 0.179044, 0.124009, 0.067234, 0.028532);\n"
                                       "\n"
                                       "out lowp vec4 color;\n"
                                       "\n"
                                       "void main() {\n"
                                       "    ivec2 center = ivec2(gl_FragCoord.xy);\n"
                                       "\n"
                                       "    vec3 result = texelFetch(tex, center, 0).rgb * weight[0];\n"
                                       "\n"
                                       "    if (horizontal) {\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(1, 0)).rgb * weight[1];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(-1, 0)).rgb * weight[1];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(2, 0)).rgb * weight[2];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(-2, 0)).rgb * weight[2];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(3, 0)).rgb * weight[3];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(-3, 0)).rgb * weight[3];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(4, 0)).rgb * weight[4];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(-4, 0)).rgb * weight[4];\n"
                                       "    } else {\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, 1)).rgb * weight[1];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, -1)).rgb * weight[1];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, 2)).rgb * weight[2];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, -2)).rgb * weight[2];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, 3)).rgb * weight[3];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, -3)).rgb * weight[3];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, 4)).rgb * weight[4];\n"
                                       "        result += texelFetchOffset(tex, center, 0, ivec2(0, -4)).rgb * weight[4];\n"
                                       "    }\n"
                                       "\n"
                                       "    color = vec4(result, 1.0);\n"
                                       "}\n"
                                       "";
const char *const BlurVertexSource = ""
#if TARGET_OS_IPHONE
                                     "#version 300 es\n"
#else
                                     "#version 330\n"
#endif
                                     "in highp vec2 position;\n"
                                     "\n"
                                     "void main() {\n"
                                     "    gl_Position = vec4(position, 0, 1);\n"
                                     "}\n"
                                     "";
const char *const CanvasFragmentSource = ""
#if TARGET_OS_IPHONE
                                         "#version 300 es\n"
#else
                                         "#version 330\n"
#endif
                                         "precision highp float;\n"
                                         "\n"
                                         "in highp vec2 fragUV;\n"
                                         "\n"
                                         "uniform sampler2D tex;\n"
                                         "uniform vec4 color;\n"
                                         "\n"
                                         "out lowp vec4 outputColor;\n"
                                         "\n"
                                         "void main() {\n"
                                         "    outputColor = color * texture(tex, fragUV);\n"
                                         "}\n"
                                         "";
const char *const CanvasVertexSource = ""
#if TARGET_OS_IPHONE
                                       "#version 300 es\n"
#else
                                       "#version 330\n"
#endif
                                       "precision highp float;\n"
                                       "\n"
                                       "in highp vec2 xy;\n"
                                       "in highp vec2 uv;\n"
                                       "\n"
                                       "uniform vec2 resolution;\n"
                                       "\n"
                                       "out highp vec2 fragUV;\n"
                                       "\n"
                                       "void main() {\n"
                                       "    gl_Position = vec4((xy / resolution - 0.5) * 2.0, 0, 1);\n"
                                       "    fragUV = uv;\n"
                                       "}\n"
                                       "";
const char *const CopyFragmentSource = ""
#if TARGET_OS_IPHONE
                                       "#version 300 es\n"
#else
                                       "#version 330\n"
#endif
                                       "precision highp float;\n"
                                       "\n"
                                       "in highp vec2 uv;\n"
                                       "\n"
                                       "uniform sampler2D tex;\n"
                                       "\n"
                                       "out lowp vec4 color;\n"
                                       "\n"
                                       "void main() {\n"
                                       "    color = texture(tex, uv);\n"
                                       "}\n"
                                       "";
const char *const CopyVertexSource = ""
#if TARGET_OS_IPHONE
                                     "#version 300 es\n"
#else
                                     "#version 330\n"
#endif
                                     "in highp vec2 position;\n"
                                     "out highp vec2 uv;\n"
                                     "\n"
                                     "void main() {\n"
                                     "    gl_Position = vec4(position, 0, 1);\n"
                                     "    uv = (position.xy + vec2(1, 1)) / 2.0;\n"
                                     "}\n"
                                     "";
const char *const DecayFragmentSource = ""
#if TARGET_OS_IPHONE
                                        "#version 300 es\n"
#else
                                        "#version 330\n"
#endif
                                        "precision highp float;\n"
                                        "\n"
                                        "uniform float decay;\n"
                                        "uniform sampler2D tex;\n"
                                        "\n"
                                        "out lowp vec4 color;\n"
                                        "\n"
                                        "void main() {\n"
                                        "    vec3 pixel = texelFetch(tex, ivec2(gl_FragCoord.xy), 0).xyz;\n"
                                        "    color = vec4(pixel * decay, 1);\n"
                                        "}\n"
                                        "";
const char *const DecayVertexSource = ""
#if TARGET_OS_IPHONE
                                      "#version 300 es\n"
#else
                                      "#version 330\n"
#endif
                                      "in highp vec2 position;\n"
                                      "\n"
                                      "void main() {\n"
                                      "    gl_Position = vec4(position, 0, 1);\n"
                                      "}\n"
                                      "";
const char *const LineFragmentSource = ""
#if TARGET_OS_IPHONE
                                       "#version 300 es\n"
#else
                                       "#version 330\n"
#endif
                                       "precision highp float;\n"
                                       "\n"
                                       "in vec2 screenStart;\n"
                                       "in vec2 screenEnd;\n"
                                       "\n"
                                       "uniform float width;\n"
                                       "uniform float intensity;\n"
                                       "\n"
                                       "out vec4 color;\n"
                                       "\n"
                                       "float minimum_distance(vec2 a, vec2 b, vec2 p) {\n"
                                       "    // line: (b - a)*t + a\n"
                                       "    // calculate t first to see if we're on the line segment\n"
                                       "    float t = dot(normalize(b - a), p - a) / distance(a, b);\n"
                                       "    if (t > 1.0) {\n"
                                       "        return distance(p, b);\n"
                                       "    }\n"
                                       "    if (t < 0.0) {\n"
                                       "        return distance(p, a);\n"
                                       "    }\n"
                                       "    vec2 intersection = (b - a) * t + a;\n"
                                       "    return distance(intersection, p);\n"
                                       "}\n"
                                       "\n"
                                       "vec4 draw_line(vec2 start, vec2 end, vec2 point, float width) {\n"
                                       "    float d = minimum_distance(start, end, point);\n"
                                       "    float factor = exp(-pow(d / width * 4.0, 4.0));\n"
                                       "    return vec4(intensity * factor);\n"
                                       "\n"
                                       "    //    float d = minimum_distance(start, end, point);\n"
                                       "    //    if (d <= width / 2.0) {\n"
                                       "    //        float factor = 1.0;\n"
                                       "    //        if (d > width / 2.0 - 1.0) {\n"
                                       "    //            // between 0 and 1 depending on distance from line segment\n"
                                       "    //            factor = width / 2.0 - d;\n"
                                       "    //        }\n"
                                       "    //        return vec4(intensity * factor);\n"
                                       "    //    } else {\n"
                                       "    //        return vec4(0, 0, 0, 0);\n"
                                       "    //    }\n"
                                       "}\n"
                                       "\n"
                                       "void main() {\n"
                                       "    color = draw_line(screenStart, screenEnd, vec2(gl_FragCoord.x, gl_FragCoord.y), width);\n"
                                       "}\n"
                                       "";
const char *const LineVertexSource = ""
#if TARGET_OS_IPHONE
                                     "#version 300 es\n"
#else
                                     "#version 330\n"
#endif
                                     "precision highp float;\n"
                                     "\n"
                                     "in vec2 start;\n"
                                     "in vec2 end;\n"
                                     "\n"
                                     "uniform mat3 transform;\n"
                                     "uniform vec2 resolution;\n"
                                     "uniform float width;\n"
                                     "uniform vec2 offset;\n"
                                     "\n"
                                     "out vec2 screenStart;\n"
                                     "out vec2 screenEnd;\n"
                                     "\n"
                                     "void main() {\n"
                                     "    vec2 clipStart = vec2(transform * vec3(start + offset, 1));\n"
                                     "    vec2 clipEnd = vec2(transform * vec3(end + offset, 1));\n"
                                     "    screenStart = (vec2(clipStart) + 1.0) / 2.0 * resolution;\n"
                                     "    screenEnd = (vec2(clipEnd) + 1.0) / 2.0 * resolution;\n"
                                     "\n"
                                     "    vec2 traverse = normalize(screenEnd - screenStart) * width * 5.0 / 2.0;\n"
                                     "    vec2 normal = vec2(traverse.y, -traverse.x);\n"
                                     "    // so these are orthogonal in screen space now, need to convert to clip space to apply to the line\n"
                                     "    traverse = traverse / resolution * 2.0;\n"
                                     "    normal = normal / resolution * 2.0;\n"
                                     "\n"
                                     "    vec2 pos;\n"
                                     "    switch (gl_VertexID % 6) {\n"
                                     "        case 0:\n"
                                     "            pos = clipStart - traverse - normal;\n"
                                     "            break;\n"
                                     "        case 1:\n"
                                     "            pos = clipEnd + traverse - normal;\n"
                                     "            break;\n"
                                     "        case 2:\n"
                                     "            pos = clipStart - traverse + normal;\n"
                                     "            break;\n"
                                     "        case 3:\n"
                                     "            pos = clipEnd + traverse + normal;\n"
                                     "            break;\n"
                                     "        case 4:\n"
                                     "            pos = clipEnd + traverse - normal;\n"
                                     "            break;\n"
                                     "        case 5:\n"
                                     "            pos = clipStart - traverse + normal;\n"
                                     "            break;\n"
                                     "    }\n"
                                     "    gl_Position = vec4(pos, 0, 1);\n"
                                     "}\n"
                                     "";
const char *const ThresholdFragmentSource = ""
#if TARGET_OS_IPHONE
                                            "#version 300 es\n"
#else
                                            "#version 330\n"
#endif
                                            "precision highp float;\n"
                                            "\n"
                                            "in highp vec2 uv;\n"
                                            "\n"
                                            "uniform sampler2D tex;\n"
                                            "\n"
                                            "out lowp vec4 color;\n"
                                            "\n"
                                            "#define THRESHOLD 0.5\n"
                                            "\n"
                                            "void main() {\n"
                                            "    vec3 pixel = texture(tex, uv).xyz;\n"
                                            "    if (pixel.x > THRESHOLD) {\n"
                                            "        color = vec4((pixel - THRESHOLD) / (1.0 - THRESHOLD), 1.0);\n"
                                            "    } else {\n"
                                            "        color = vec4(0.0, 0.0, 0.0, 1.0);\n"
                                            "    }\n"
                                            "}\n"
                                            "";
const char *const ThresholdVertexSource = ""
#if TARGET_OS_IPHONE
                                          "#version 300 es\n"
#else
                                          "#version 330\n"
#endif
                                          "in highp vec2 position;\n"
                                          "out highp vec2 uv;\n"
                                          "\n"
                                          "void main() {\n"
                                          "    gl_Position = vec4(position, 0, 1);\n"
                                          "    uv = (position.xy + vec2(1, 1)) / 2.0;\n"
                                          "}\n"
                                          "";
