/* This file was automatically generated.  Do not edit! */
#define global_variable static
#define local_persist static
#define internal static
typedef double float64;
typedef float float32;
typedef size_t memory_index;
typedef uintptr_t uintptr;
typedef intptr_t intptr;
typedef uint64_t uint64;
typedef uint32_t uint32;
typedef uint16_t uint16;
typedef uint8_t uint8;
typedef int32_t int32;
typedef int32 bool32;
typedef int64_t int64;
typedef int16_t int16;
typedef int8_t int8;
#define INTERFACE 0
